FROM docker.io/library/haproxy:2.3

ADD https://raw.githubusercontent.com/cmason3/jinjafx/main/jinjafx_server/docker/haproxy.cfg /usr/local/etc/haproxy/
RUN chown haproxy:haproxy /usr/local/etc/haproxy/haproxy.cfg

USER haproxy
