FROM docker.io/library/haproxy:1.8

USER root

ADD https://raw.githubusercontent.com/cmason3/jinjafx/main/jinjafx_server/docker/haproxy.cfg /usr/local/etc/haproxy/

ENTRYPOINT [ "/usr/local/sbin/haproxy", "-f", "/usr/local/etc/haproxy/haproxy.cfg" ]
