FROM python:3.8-slim

ARG BRANCH="master"

RUN apt-get update; apt-get install -y git; apt-get clean
RUN python3 -m pip --disable-pip-version-check --no-cache-dir install --upgrade ansible netaddr requests

RUN git clone -b "${BRANCH}" https://github.com/cmason3/jinjafx.git /opt/jinjafx

RUN useradd -m jinjafx
USER jinjafx

WORKDIR /opt/jinjafx

ENTRYPOINT [ "/usr/local/bin/python3", "-u", "jinjafx_server/jinjafx_server.py", "-s", "-l", "0.0.0.0", "-p", "8080" ]
