FROM python:3.8-slim

RUN apt-get update; apt-get install -y curl git; apt-get clean
RUN python3 -m pip --no-cache-dir install --upgrade ansible netaddr

RUN git clone -b "master" https://github.com/cmason3/jinjafx.git /opt/jinjafx

RUN useradd -m jinjafx
USER jinjafx

WORKDIR /opt/jinjafx

HEALTHCHECK --interval=5m --timeout=3s CMD curl -f http://localhost:8080/ping || exit 1
ENTRYPOINT [ "/usr/local/bin/python3", "-u", "jinjafx_server.py", "-s", "-l", "0.0.0.0", "-p", "8080" ]
