FROM python:3.8-slim

RUN apt-get update; apt-get install -y curl git; apt-get clean
RUN python3 -m pip --disable-pip-version-check --no-cache-dir install --upgrade ansible netaddr

RUN git clone -b "master" https://github.com/cmason3/jinjafx.git /opt/jinjafx

RUN useradd -m jinjafx
USER jinjafx

WORKDIR /opt/jinjafx

ENTRYPOINT [ "/usr/local/bin/python3", "-u", "jinjafx_server.py", "-s", "-l", "0.0.0.0", "-p", "8080" ]
